angular.module(
  'client',
  [
    'ngSanitize',
    'ui.router',
    'templates',
    'ngResource',
    'ngAnimate',
    'ngEnter',
    'angular-growl',
    'NgActive',
    'infinite-scroll',
    'tableSort',
    'tagged.directives.infiniteScroll'
  ]
)
